### ISSUE TITLE
Experiment Hangs Latest FPSci Build

### ISSUE THREAD

**Issue by David-Durst** [jspjutNV/latencyExpEHPHCI21#1]
I'm having some trouble running this experiment. Please let me know if I'm running it wrong. I'm trying to run it on a version of FPSci built from source rather than the distributed binary described in the [How to run section](https://github.com/jspjutNV/latencyExpEHPHCI21#how-to-run). Thank you for your help!

**Problem:** running this experiment when building FPSci from commit https://github.com/NVlabs/FPSci/commit/3db1b4998917cfa5eb639ffff0da1891f34a40d5 causes FPSci to hang with a black screen.

**How To Reproduce:** Checkout https://github.com/NVlabs/FPSci/commit/3db1b4998917cfa5eb639ffff0da1891f34a40d5, copy [the configs folder](https://github.com/jspjutNV/latencyExpEHPHCI21/tree/master/configs) into [FPSci's data-files folder](https://github.com/NVlabs/FPSci/tree/master/data-files), and run the code in VS2019's debug mode

**Comment by jspjut** [comment]
I probably should update the readme on this one. This experiment is designed against the particular version of FPSci that the script grabs, and would need modification to work with more recent FPSci versions (which is why the script grabs a specific version).

However, the FPSci version this experiment uses has a bug that messes some things up if you're playing around too much with it. We don't believe that bug was messing things up during the published study, but it makes it particularly obnoxious to fiddle with. I'm not sure updating this specific experiment is high priority, but I do think it would be good to provide similar styles of experiments for use with the latest FPSci that we maintain as samples to start from.

I just created https://github.com/NVlabs/FPSci/issues/307 to track this, and hopefully we'll be able to create a new release to provide some of these by the end of the week.

**Comment by David-Durst** [comment]
That makes sense. I don't need exactly this experiment. I'll close this issue since it's roughly a duplicate of NVlabs/FPSci#307.
